targets:
  $default:
    sources:
      - bin/**
      - lib/**
      - web/**
      # Note that it is important to include these in the default target.
      - pubspec.*
      - $package$
    builders:
      drift_dev:
        options:
          generate_connect_constructor: true