name: inside_data
description: Manage data for Inside Chassidus
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter_wordpress:
    git:
      #url: https://github.com/dreamsoftin/flutter_wordpress
      url: https://github.com/yringler/flutter_wordpress/
      ref: new-master
  json_annotation: ^4.8.1
  http: ^1.1.0
  html: ^0.15.0
  html_unescape: ^2.0.0
  rxdart: ^0.27.3
  drift: ^2.10.0
  sqlite3_flutter_libs: ^0.5.2
  dio_cache_interceptor: ^3.1.0
  dio: ^5.3.2
  collection: ^1.17.1
  connectivity_plus: ^4.0.2
  flutter_fgbg: ^0.3.0
  quiver: ^3.2.1

dev_dependencies: 
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  drift_dev: ^2.10.0
